### PR TITLE
auto blur button on click, btn-default disabled and focus shows spinn…

### PR DESCRIPTION
**Pull request by lookbadgers**
…er white on white background, blur allows background to change colour and spinner to appear as white on grey

### CODE REVIEW

**Comment by lookbadgers** [comment]
If a button has btn-default the spinners does not show up if the spinner is triggered on click.  The spinner shows as white on white.

This fix means when ever a spinner starts, the button is blurred.  Therefore avoiding the spinner not showing up for btn-default.

The alternative solution would be to manually call blur() before every ladda('start').  If a button is disabled it does not make sense for it to have focus, therefore it seems better that ladda manages this as well.

```
        <button type="button" class="btn btn-default ladda-button" data-style="zoom-in">
            <span class="ladda-label">
                <span class="glyphicon glyphicon-pencil"></span>
            </span>
        </button>
```

**Comment by terales** [comment]
Problem reproduced in JSFiddle: https://jsfiddle.net/terales/5v2v0mgL/1/

But I don't see how proposed fix helps, see JSFiddle with `ladda.js` from `lookbadgers/ladda-bootstrap`: https://jsfiddle.net/terales/5v2v0mgL/2/

@lookbadgers can you update JSFiddle to reproduce a solution, please?

**Comment by terales** [comment]
@msurguy I think this PR could be closed in favor of https://github.com/msurguy/ladda-bootstrap/issues/65#issuecomment-354715403: use `data-spinner-color` attribute to change color of `btn-default`

**Comment by msurguy** [comment]
@terales thanks! That makes it easy to find if somebody's looking!

**Pull request closed without merging**
